from sqlalchemy import Column, Numeric, String, DateTime, Text, Integer, func
from sqlalchemy.ext.declarative import declarative_base
from geoalchemy2 import Geometry
import datetime

Base = declarative_base()


class Fires(Base):
    __tablename__ = 'fires'
    id = Column(Integer, primary_key=True)
    scrape_date = Column(DateTime)
    source = Column(String)
    lat = Column(Numeric)
    lon = Column(Numeric)
    name = Column(String)
    acres = Column(Numeric)
    published_date = Column(DateTime)
    start_date = Column(String)
    last_updated = Column(DateTime)
    summary = Column(Text)
    remarks = Column(Text)
    location_description = Column(Text)
    containment = Column(String)
    estimated_contained_date = Column(DateTime)
    ros = Column(String)
    roc = Column(String)
    alternate_name = Column(String)
    country = Column(String)
    state = Column(String)
    city = Column(String)
    region = Column(String)
    county = Column(String)
    fire_number = Column(String)
    initial_attack_acres = Column(Numeric)
    fuel_type = Column(String)
    conditions = Column(String)
    land_owner = Column(String)
    life_threatened = Column(String)
    structures_threatened = Column(String)
    structures_destroyed = Column(String)
    road_closures = Column(String)
    evacuations = Column(String)
    special_hazards = Column(String)
    injuries_reported = Column(String)
    details_summary = Column(Text)
    incident_commander = Column(String)
    type = Column(String)
    planned_actions = Column(Text)
    source_url = Column(String)
    irwin_id = Column(String)
    inciweb_id = Column(Integer)
    calfire_id = Column(Integer)
    description = Column(Text)
    hashtag = Column(String)
    geom = Column(Geometry)
